main: emd_bonneel.cpp full_bipartitegraph.h network_simplex_simple.h
	g++ -std=c++14 -shared -fpic -Ofast -march=native -fno-signed-zeros -fno-trapping-math -frename-registers -funroll-loops emd_bonneel.cpp -o emd_bonneel.so
